system:
  db-type: mysql
  oss-type: local
  router-prefix: ""
  addr: 8080
  iplimit-count: 15000
  iplimit-time: 3600
  use-multipoint: false
  use-redis: true
  use-strict-auth: false

captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600

jwt:
  signing-key: 3e68ba3c-bae0-476f-9d11-a698f91866fe
  expires-time: 7d
  buffer-time: 1d
  issuer: kubegale

zap:
  level: info
  prefix: '[KUBEGALE]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
  retention-day: -1

mysql:
  prefix: ""
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: kubegale
  username: root
  password: "123456"
  path: 127.0.0.1
  engine: ""
  log-mode: info
  max-idle-conns: 10
  max-open-conns: 100
  singular: false
  log-zap: true

redis:
  name: ""
  addr: 127.0.0.1:6379
  password: ""
  db: 0
  useCluster: false
  clusterAddrs:
    - 172.21.0.3:7000
    - 172.21.0.4:7001
    - 172.21.0.2:7002
redis-list:
  - name: cache
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
      - 172.21.0.3:7000
      - 172.21.0.4:7001
      - 172.21.0.2:7002